[package]
name = "bool_module"
type = "contract"
authors = [""]
compiler_version = ">=0.29.0"

[dependencies]
aztec = { git = "https://github.com/AztecProtocol/aztec-packages/", tag = "aztec-packages-v0.41.0", directory = "noir-projects/aztec-nr/aztec" }
