[package]
name = "event"
type = "contract"
authors = [""]
compiler_version = ">=0.29.0"

[dependencies]
aztec = { git = "https://github.com/AztecProtocol/aztec-packages/", tag = "aztec-packages-v0.41.0", directory = "noir-projects/aztec-nr/aztec" }
value_note = { git = "https://github.com/AztecProtocol/aztec-packages/", tag = "aztec-packages-v0.41.0", directory = "noir-projects/aztec-nr/value-note" }
easy_private_state = { git = "https://github.com/AztecProtocol/aztec-packages/", tag = "aztec-packages-v0.41.0", directory = "noir-projects/aztec-nr/easy-private-state" }
authwit = { git = "https://github.com/AztecProtocol/aztec-packages/", tag = "aztec-packages-v0.41.0", directory = "noir-projects/aztec-nr/authwit" }
protocol_types = { git = "https://github.com/AztecProtocol/aztec-packages/", tag = "aztec-packages-v0.41.0", directory = "noir-projects/noir-protocol-circuits/crates/types" }
links = { path = "../links" }
